[mypy]
python_version = 3.10
ignore_missing_imports = True
warn_unused_ignores = False
check_untyped_defs = True
namespace_packages = True
explicit_package_bases = True

[mypy-aiokafka.*]
ignore_missing_imports = True

[mypy-langgraph.*]
ignore_missing_imports = True

[mypy-langchain_core.*]
ignore_missing_imports = True

[mypy-langchain_aws.*]
ignore_missing_imports = True
